In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Load dataset
from sklearn.datasets import load_iris

# Train-test split
from sklearn.model_selection import train_test_split

# Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Evaluation metrics
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score
)

In [ ]:
# Load IRIS dataset
iris = load_iris()

# Convert into DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add target column
df['species'] = iris.target

# Display first 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Features (inputs)
X = df.drop('species', axis=1)

# Target (output)
y = df['species']

# Display first 5 rows
print("Features:")
print(X.head())

print("--------------")

print("\nTarget:")
print(y.head())

Features:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
--------------

Target:
0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [ ]:
# Split dataset into training and testing

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display shapes
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (120, 4)
X_test: (30, 4)
y_train: (120,)
y_test: (30,)

In [ ]:
# Create Gaussian Naive Bayes model
#GaussianNB is used for classification of continuous numerical data

model = GaussianNB()

print("Gaussian Naive Bayes Model Created it")

Gaussian Naive Bayes Model Created it

In [ ]:
# Train model ,small->setosa

model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

In [ ]:
# Predict species using test data

y_pred = model.predict(X_test)

# Display first 10 predictions
print(y_pred[:10])

[1 0 2 1 1 0 1 2 1 1]

In [ ]:
# Create confusion matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

                MODEL PREDICTION

              SETOSA  VERSI  VIRGINICA

ACTUAL SETOSA    10      0        0

ACTUAL VERSI      0      9        1

ACTUAL VIRGINICA  0      2        8

In [ ]:
# Calculate accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
# Calculate precision

precision = precision_score(
    y_test,
    y_pred,
    average='macro'
)

print("Precision:", precision)

Precision: 1.0

In [ ]:
# Calculate recall

recall = recall_score(
    y_test,
    y_pred,
    average='macro'
)

print("Recall:", recall)

Recall: 1.0

In [ ]:
# Create comparison table

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

# Display first 10 rows
comparison.head(10)

   Actual  Predicted
0       1          1
1       0          0
2       2          2
3       1          1
4       1          1
5       0          0
6       1          1
7       2          2
8       1          1
9       1          1